spring:
  application:
    name: movie-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-51969336.okta.com/oauth2/default/v1/keys
          issuer-uri: https://dev-51969336.okta.com/oauth2/default
server:
    port: 8087
restClient:
  moviesInfoUrl: lb://car-service/v1/movieInfos
  reviewsUrl: lb://car-service/v1/reviews
---
spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile:
        - local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
---
spring:
  config:
    activate:
      on-profile:
        - non-prod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
logging:
  level:
    root: info
    de.flapdoodle.os.common.attributes: warn